import { SymbolCatalogItem } from '../../types/electrical';

export const SYMBOL_CATEGORIES = [
  { id: 'all', label: 'Todos los Equipos', icon: 'Layers' },
  { id: 'acometida', label: 'Acometida & Medición', icon: 'Zap' },
  { id: 'proteccion', label: 'Protecciones & Breakers', icon: 'ShieldAlert' },
  { id: 'conductor', label: 'Conductores & Tuberías', icon: 'Cable' },
  { id: 'transformacion', label: 'Transformadores & Motores', icon: 'Cpu' },
  { id: 'carga', label: 'Tableros & Cargas', icon: 'LayoutGrid' },
] as const;

export const ELECTRICAL_SYMBOLS_CATALOG: SymbolCatalogItem[] = [
  // 1. Acometida & Medición
  {
    type: 'acometida_aerea',
    name: 'Acometida Aérea',
    category: 'acometida',
    categoryLabel: 'Acometida & Medición',
    description: 'Punto de entrega aéreo desde poste de distribución secundaria/primaria.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 1200,
      currentLoadAmps: 850,
      phases: 1,
      conductorGauge: '500 kcmil',
      conductorMaterial: 'Cu',
      conduitSize: '4"',
      conduitType: 'RMC',
      distanceMeters: 18,
      loadPowerKW: 180,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'ACOM-01',
    },
    iconName: 'Zap',
    symbolBadge: '⚡ Acometida',
  },
  {
    type: 'acometida_subterranea',
    name: 'Acometida Subterránea',
    category: 'acometida',
    categoryLabel: 'Acometida & Medición',
    description: 'Acometida bajo tierra con ducto PVC Schedule 40 y registro de inspección.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 1200,
      currentLoadAmps: 920,
      phases: 1,
      conductorGauge: '500 kcmil',
      conductorMaterial: 'Cu',
      conduitSize: '4"',
      conduitType: 'PVC',
      distanceMeters: 30,
      loadPowerKW: 200,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'ACOM-SUB',
    },
    iconName: 'ArrowDownCircle',
    symbolBadge: '⬇ Subterránea',
  },
  {
    type: 'medidor',
    name: 'Medidor kWh Monofásico',
    category: 'acometida',
    categoryLabel: 'Acometida & Medición',
    description: 'Vatímetro para facturación de energía según normas ENSA/Naturgy.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 200,
      currentLoadAmps: 140,
      phases: 1,
      conductorGauge: '#2/0 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '2"',
      conduitType: 'EMT',
      distanceMeters: 4,
      loadPowerKW: 30,
      powerFactor: 0.95,
      isClosed: true,
      meterNumber: 'MTR-2024',
      tag: 'MEDIDOR',
    },
    iconName: 'Gauge',
    symbolBadge: '⏱ Medidor kWh',
  },

  // 2. Protecciones & Breakers
  {
    type: 'interruptor_principal',
    name: 'Interruptor Principal (IP / Main Breaker)',
    category: 'proteccion',
    categoryLabel: 'Protecciones & Breakers',
    description: 'Caja moldeada principal para corte y protección general de la instalación.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 1200,
      currentLoadAmps: 950,
      phases: 1,
      conductorGauge: '500 kcmil',
      conductorMaterial: 'Cu',
      conduitSize: '4"',
      conduitType: 'RMC',
      distanceMeters: 2,
      loadPowerKW: 210,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'IP-MAIN',
    },
    iconName: 'ShieldAlert',
    symbolBadge: '🛡 IP Principal',
  },
  {
    type: 'breaker_termomagnetico',
    name: 'Breaker Termomagnético Derivado',
    category: 'proteccion',
    categoryLabel: 'Protecciones & Breakers',
    description: 'Interruptor automático 1 o 2 polos para circuitos derivados o subtableros.',
    defaultProps: {
      voltage: 120,
      ratedCurrent: 50,
      currentLoadAmps: 38,
      phases: 1,
      conductorGauge: '#6 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1"',
      conduitType: 'EMT',
      distanceMeters: 15,
      loadPowerKW: 4.5,
      powerFactor: 0.92,
      isClosed: true,
      tag: 'BRK-01',
    },
    iconName: 'ToggleRight',
    symbolBadge: '🔘 Breaker',
  },
  {
    type: 'fusible',
    name: 'Fusible de Potencia / Cortacircuito',
    category: 'proteccion',
    categoryLabel: 'Protecciones & Breakers',
    description: 'Elemento de protección por fusión rápida para alta corriente de cortocircuito.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 100,
      currentLoadAmps: 70,
      phases: 1,
      conductorGauge: '#2 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1-1/2"',
      conduitType: 'EMT',
      distanceMeters: 5,
      loadPowerKW: 16,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'FUS-01',
    },
    iconName: 'ZapOff',
    symbolBadge: '💥 Fusible',
  },

  // 3. Conductores & Tuberías
  {
    type: 'barra_distribucion',
    name: 'Barra Colectora de Cobre (Busbar)',
    category: 'conductor',
    categoryLabel: 'Conductores & Tuberías',
    description: 'Pletina maciza de cobre electrolítico para distribución general de fases y neutro.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 1200,
      currentLoadAmps: 800,
      phases: 1,
      conductorGauge: '500 kcmil',
      conductorMaterial: 'Cu',
      conduitSize: '4"',
      conduitType: 'RMC',
      distanceMeters: 1,
      loadPowerKW: 180,
      powerFactor: 0.98,
      isClosed: true,
      tag: 'BUS-1200A',
    },
    iconName: 'Rows',
    symbolBadge: '▬ Barra Busbar',
  },
  {
    type: 'conductor_fase',
    name: 'Alimentador de Fase (L1 / L2 / L3)',
    category: 'conductor',
    categoryLabel: 'Conductores & Tuberías',
    description: 'Línea de potencia con aislamiento THHN/THWN-2 a 75°C / 90°C.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 200,
      currentLoadAmps: 160,
      phases: 1,
      conductorGauge: '#3/0 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '2"',
      conduitType: 'EMT',
      distanceMeters: 25,
      loadPowerKW: 38,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'LINEA-FASE',
    },
    iconName: 'Cable',
    symbolBadge: '〰 Línea Fase',
  },
  {
    type: 'tierra_fisica',
    name: 'Electrodo Puesta a Tierra (Ground)',
    category: 'conductor',
    categoryLabel: 'Conductores & Tuberías',
    description: 'Varilla Copperweld 5/8" x 8ft con conductor de cobre desnudo para seguridad.',
    defaultProps: {
      voltage: 0,
      ratedCurrent: 200,
      currentLoadAmps: 0,
      phases: 1,
      conductorGauge: '#2 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '3/4"',
      conduitType: 'PVC',
      distanceMeters: 8,
      loadPowerKW: 0,
      powerFactor: 1.0,
      isClosed: true,
      tag: 'TIERRA-GND',
    },
    iconName: 'Anchor',
    symbolBadge: '⏚ Puesta a Tierra',
  },
  {
    type: 'tuberia_conduit',
    name: 'Canalización Tubería Conduit',
    category: 'conductor',
    categoryLabel: 'Conductores & Tuberías',
    description: 'Tubería metálica o plástica con cálculo de porcentaje de ocupación máxima.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 200,
      currentLoadAmps: 150,
      phases: 1,
      conductorGauge: '#2/0 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '2"',
      conduitType: 'EMT',
      distanceMeters: 20,
      loadPowerKW: 35,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'COND-2IN',
    },
    iconName: 'Cylinder',
    symbolBadge: '⭕ Conduit',
  },

  // 4. Transformadores & Motores
  {
    type: 'transformador',
    name: 'Transformador Monofásico / Trifásico',
    category: 'transformacion',
    categoryLabel: 'Transformadores & Motores',
    description: 'Reductor de 13.8kV/19.9kV a 240/120V o 208/120V con tomas de regulación.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 600,
      currentLoadAmps: 450,
      phases: 1,
      conductorGauge: '350 kcmil',
      conductorMaterial: 'Cu',
      conduitSize: '3"',
      conduitType: 'RMC',
      distanceMeters: 10,
      loadPowerKW: 100,
      powerFactor: 0.95,
      kvaRating: 100,
      isClosed: true,
      tag: 'XFMR-100KVA',
    },
    iconName: 'Cpu',
    symbolBadge: '🔄 Transformador',
  },
  {
    type: 'motor_electrico',
    name: 'Motor Eléctrico de Inducción',
    category: 'transformacion',
    categoryLabel: 'Transformadores & Motores',
    description: 'Carga inductiva con corriente de arranque y protección de sobrecarga térmica.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 40,
      currentLoadAmps: 34,
      phases: 1,
      conductorGauge: '#8 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1"',
      conduitType: 'EMT',
      distanceMeters: 22,
      loadPowerKW: 7.5,
      powerFactor: 0.82,
      efficiency: 0.88,
      isClosed: true,
      tag: 'MOT-10HP',
    },
    iconName: 'RotateCw',
    symbolBadge: '⚙ Motor Eléctrico',
  },
  {
    type: 'banco_capacitores',
    name: 'Banco de Capacitores',
    category: 'transformacion',
    categoryLabel: 'Transformadores & Motores',
    description: 'Compensador de potencia reactiva para elevar el factor de potencia a > 0.95.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 60,
      currentLoadAmps: 45,
      phases: 1,
      conductorGauge: '#6 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1"',
      conduitType: 'EMT',
      distanceMeters: 6,
      loadPowerKW: 15,
      powerFactor: 0.99,
      isClosed: true,
      tag: 'CAP-BANK',
    },
    iconName: 'BatteryCharging',
    symbolBadge: '🔋 Capacitores',
  },

  // 5. Tableros & Cargas
  {
    type: 'tablero_distribucion',
    name: 'Tablero de Distribución (Panelboard)',
    category: 'carga',
    categoryLabel: 'Tableros & Cargas',
    description: 'Centro de carga con barras colectoras y capacidad para interruptores bipolares/monopolares.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 200,
      currentLoadAmps: 135,
      phases: 1,
      conductorGauge: '#2/0 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '2"',
      conduitType: 'EMT',
      distanceMeters: 12,
      loadPowerKW: 28,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'TD-01',
    },
    iconName: 'LayoutGrid',
    symbolBadge: '▦ Tablero Distribución',
  },
  {
    type: 'carga_general',
    name: 'Carga General / Alumbrado y Tomas',
    category: 'carga',
    categoryLabel: 'Tableros & Cargas',
    description: 'Consumo eléctrico de receptáculos, luminarias y equipos auxiliares.',
    defaultProps: {
      voltage: 120,
      ratedCurrent: 20,
      currentLoadAmps: 14,
      phases: 1,
      conductorGauge: '#12 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '3/4"',
      conduitType: 'EMT',
      distanceMeters: 18,
      loadPowerKW: 1.6,
      powerFactor: 0.98,
      isClosed: true,
      tag: 'CKT-ALUM',
    },
    iconName: 'Power',
    symbolBadge: '🔌 Carga General',
  },
  // 6. Control y Maniobra Magnética
  {
    type: 'contactor',
    name: 'Contactor Magnético',
    category: 'control',
    categoryLabel: 'Mando y Control',
    description: 'Dispositivo electromecánico para control de motores y cargas de potencia.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 50,
      currentLoadAmps: 34,
      phases: 1,
      conductorGauge: '#8 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1"',
      conduitType: 'EMT',
      distanceMeters: 5,
      loadPowerKW: 7.5,
      powerFactor: 0.85,
      isClosed: false,
      tag: 'KM1',
    },
    iconName: 'ToggleLeft',
    symbolBadge: '🧲 Contactor',
  },
  {
    type: 'rele_termico',
    name: 'Relé Térmico de Sobrecarga',
    category: 'control',
    categoryLabel: 'Mando y Control',
    description: 'Protección contra sobrecargas prolongadas en motores.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 40,
      currentLoadAmps: 34,
      phases: 1,
      conductorGauge: '#8 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1"',
      conduitType: 'EMT',
      distanceMeters: 1,
      loadPowerKW: 7.5,
      powerFactor: 0.85,
      isClosed: true,
      tag: 'RT1',
    },
    iconName: 'Thermometer',
    symbolBadge: '🌡 Relé Térmico',
  },
  {
    type: 'pulsador',
    name: 'Pulsador (NO / NC)',
    category: 'control',
    categoryLabel: 'Mando y Control',
    description: 'Botón de mando para marcha o parada de circuitos de control.',
    defaultProps: {
      voltage: 120,
      ratedCurrent: 10,
      currentLoadAmps: 1,
      phases: 1,
      conductorGauge: '#14 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1/2"',
      conduitType: 'EMT',
      distanceMeters: 10,
      loadPowerKW: 0.1,
      powerFactor: 1.0,
      isClosed: false,
      tag: 'S1-START',
    },
    iconName: 'CircleDot',
    symbolBadge: '🔘 Pulsador',
  },
  {
    type: 'plc',
    name: 'Módulo PLC',
    category: 'control',
    categoryLabel: 'Mando y Control',
    description: 'Controlador Lógico Programable para automatización.',
    defaultProps: {
      voltage: 120,
      ratedCurrent: 15,
      currentLoadAmps: 5,
      phases: 1,
      conductorGauge: '#14 AWG',
      conductorMaterial: 'Cu',
      conduitSize: '1/2"',
      conduitType: 'EMT',
      distanceMeters: 2,
      loadPowerKW: 0.5,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'PLC-MAIN',
    },
    iconName: 'Server',
    symbolBadge: '🖥 PLC',
  },
  // 7. Canalizaciones y Cajas
  {
    type: 'canaleta',
    name: 'Canaleta o Bandeja Portacables',
    category: 'canalizacion',
    categoryLabel: 'Canalizaciones & Cajas',
    description: 'Soporte físico para ruteo de múltiples cables.',
    defaultProps: {
      voltage: 0,
      ratedCurrent: 0,
      currentLoadAmps: 0,
      phases: 1,
      conductorGauge: 'N/A',
      conductorMaterial: 'Cu',
      conduitSize: '4x4"',
      conduitType: 'Bandeja',
      distanceMeters: 50,
      loadPowerKW: 0,
      powerFactor: 1,
      isClosed: true,
      tag: 'B-TRAY',
    },
    iconName: 'Kanban',
    symbolBadge: '🛤 Bandeja',
  },
  {
    type: 'caja_ct',
    name: 'Caja CT / Medición Indirecta',
    category: 'canalizacion',
    categoryLabel: 'Canalizaciones & Cajas',
    description: 'Gabinete para transformadores de corriente en alta carga.',
    defaultProps: {
      voltage: 240,
      ratedCurrent: 1200,
      currentLoadAmps: 1000,
      phases: 1,
      conductorGauge: '500 kcmil',
      conductorMaterial: 'Cu',
      conduitSize: '4"',
      conduitType: 'RMC',
      distanceMeters: 1,
      loadPowerKW: 200,
      powerFactor: 0.95,
      isClosed: true,
      tag: 'CT-BOX',
    },
    iconName: 'Box',
    symbolBadge: '🗄 Caja CT',
  },
];
